### PR TITLE
Experimental TIG support and more

### PR DESCRIPTION
**Pull request by hogthrob**
This PR is not meant for direct acceptance but should rather be an indicator of what I am currently working on and serve as "discussion thread". 
All but the last commits could be included without much risk as these are only refactoring or small general purpose helper functions. 

THIS IS EXPERIMENTAL CODE!

Added startup situation analysis, which detects short circuit and if
a working shutdown pin is available. In case of short current is switched off or
at least reduced to the min (if no shutdown pin is available).
Result of analysis is also shown by second "heart" icon.

Added arc state detection, which detects short, metal touched , open, arc running
Used with experiemental TIG code for lift start (lift start requires a lower
than minimal current setting).
Will be useful for stick welding ( Arc Stick and Hot Start).

Added preliminary mode switch page (in place of the info page), refactored
UI code to make it easier to add pages without repeated code standard code
using some C++ concepts.

### CODE REVIEW

**Comment by thomastech** [comment]
Great to see the progress on your new TIG mode feature. I've created a discussion area on the rc-cam forum for you. It is intended to discuss the TIG hardware.
https://www.rc-cam.com/forum/index.php?/topic/4710-add-tig-function-to-the-sparky-stick-welder/

As with the original Sparky project, please use the GitHub repo for software related items. But use the rc-cam forum to discuss the hardware. 

I think you will find that the forum is great place for the hardware technical discussions. And I prefer that Sparky's GitHub repo be dedicated to the software version control and distribution.

If you prefer to discuss the Sparky TIG hardware at your own host then please kindly add a link to it at the rc-cam forum's TIG topic (at link posted above). This will allow others to easily find your work.

I will leave this PR open so you can use it to share/discuss your experimental code. And just ask if you need me to collaborate as a reviewer. I will help out where I can if you desire any external input. Otherwise I'll sit back and watch your magic happen.

- Thomas

**Comment by hogthrob** [comment]
What you could do to help:
- enable PWM_ARC_CTRL. The code should now detect that you don't have a working connection and behave as if it was not enabled via the DEFINE. This detection works only if there is no short when starting the machine. disableArc() tries to stay on the safe side when using the detection results.

- When turning the machine on and a short is already present, it should go to "ARC OFF" and home page should be blue.

**Comment by thomastech** [comment]
> What you could do to help: ...

I will test your code sometime this week. 

Be aware that this welder does not have soft start. So turning it on with shorted welding cables adds more strain to the already brutal startup current. The stress can increase the chance of power switch failure (contacts weld shut, will no longer turn off).

- Thomas

**Comment by hogthrob** [comment]
Well, I added a manually operated external mains soft start circuit to the setup. Basically a switchable power socket with an added inrush limiting NTC (1 ohm) across the switch. Switch open -> NTC active, switch closed -> NTC not being used.  Since then I had no issues with breakers being activated when starting the welder with the NTC active.  A "normal" resistor of sufficient wattage would also work but would have to be much larger as it doesn't reduce its resistance under load very much.

**Comment by thomastech** [comment]
> Well, I added a manually operated external mains soft start circuit to the setup. Basically a switchable power socket with an added inrush limiting NTC (1 ohm) across the switch.

Nice simple solution.

- Thomas

**Comment by thomastech** [comment]
Test results on arc short boot test:
* Arc current is disabled (blue home page).
* New drawPinState() heart graphic is orange (normally red).  Note: I did not wire the hardware shutdown to the SG3525A chip.

 Thomas

**Comment by hogthrob** [comment]
@thomastech : Thanks a lot, that was what should happen.
Orange indicates short detected. Red -> no shutdown pin detected, blue -> shutdown pin working.
The test is done by disabling the PWM and testing if the current AND voltage drop to 0. As the current is normally enabled anyways, not really an issue enabling the current even if the ARC_OFF mode was selected.
 
 

The 2nd heart indicator is just a temporary approach for indicating the "self-test/health" state. Not sure if and how we finally should show this kind of information.

**Comment by thomastech** [comment]
Lot's of choices for the icon. Besides fancy bitmap icons it could be a small colored rectangle with a single char in it (using library graphics).
 S = Short Circuit (orange)
 P = Pin detected (blue)
 N = No Pin detected (red)

But to reduce screen clutter I recommended not displaying the Pin detected (normal) condition. Just show Short and No Pin warnings since these are elevated warnings.

- Thomas

**Pull request closed without merging**
